version = 0.1
[default.pipeline_bootstrap.parameters]
oidc_provider_url = "https://token.actions.githubusercontent.com"
oidc_client_id = "sts.amazonaws.com"
github_org = "maahdisrostampoor"
github_repo = "MovieLens"
deployment_branch = "main"
oidc_provider = "github-actions"
permissions_provider = "OpenID Connect (OIDC)"

[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::381492285923:role/3"
cloudformation_execution_role = "arn:aws:iam::381492285923:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionRo-w8faWVZpG2wg"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-r-artifactsbucket-hkgixjbuzwh8"
image_repository = ""
region = "us-east-1"

[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::381492285923:role/aws-sam-cli-managed-prod-pipe-PipelineExecutionRole-nqfCgyJpQeCe"
cloudformation_execution_role = "arn:aws:iam::381492285923:role/aws-sam-cli-managed-prod--CloudFormationExecutionRo-XyodNvEhsqDv"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline--artifactsbucket-bmcqaivt57h4"
image_repository = ""
region = "us-east-1" 
