version = 0.1
[default.pipeline_bootstrap.parameters]
oidc_provider_url = "https://token.actions.githubusercontent.com"
oidc_client_id = "sts.amazonaws.com"
github_org = "maahdisrostampoor"
github_repo = "MovieLens"
deployment_branch = "main"
oidc_provider = "github-actions"
permissions_provider = "OpenID Connect (OIDC)"

[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::381492285923:role/aws-sam-cli-managed-dev-pipel-PipelineExecutionRole-XM0aJ7MjPelh"
cloudformation_execution_role = "arn:aws:iam::381492285923:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionRo-aXboLQAtpP21"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-r-artifactsbucket-xdic9oh3ats9"
image_repository = ""
region = "us-east-1"

[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::381492285923:role/aws-sam-cli-managed-prod-pipe-PipelineExecutionRole-xyqGyrFe5XEP"
cloudformation_execution_role = "arn:aws:iam::381492285923:role/aws-sam-cli-managed-prod--CloudFormationExecutionRo-WiqrgKgftpTn"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline--artifactsbucket-y1a99wc8nefw"
image_repository = ""
region = "us-east-1"
